# Generated by Django 3.2.4 on 2021-10-25 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='report.reportitem'),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Reporter')], verbose_name='Phân quyền'),
        ),
    ]
