# Generated by Django 3.2.4 on 2021-10-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20211025_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportitem',
            name='costCenter',
        ),
        migrations.AddField(
            model_name='budgettransaction',
            name='costCenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.costcenter', verbose_name='Cost Center'),
        ),
    ]
