# Generated by Django 3.2.4 on 2021-10-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20211025_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportitem',
            name='formular',
            field=models.CharField(max_length=255, null=True, verbose_name='Công thức'),
        ),
    ]
