# Generated by Django 3.2.4 on 2021-10-25 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_reportitem_formular'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='reportitem',
            name='formular',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Công thức'),
        ),
        migrations.AddField(
            model_name='reportitem',
            name='costCenterCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.costcentercategory'),
        ),
    ]
