# Generated by Django 3.2.4 on 2021-11-07 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20211025_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='costCenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.costcenter', verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'General Manager'), (3, 'Head Of Department')], verbose_name='Phân quyền'),
        ),
        migrations.AlterField(
            model_name='reportitem',
            name='costCenterCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.costcentercategory', verbose_name='Nhóm Costcenter'),
        ),
        migrations.AlterField(
            model_name='reportitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='report.reportitem', verbose_name='Danh mục cha'),
        ),
    ]
