# Generated by Django 3.2.4 on 2021-11-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20211107_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='costCenterCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.costcentercategory', verbose_name='Danh mục Costcenter'),
        ),
    ]
